// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using module_20.DAL.EntityFramework;

namespace module_20.DAL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200121120637_UpdateDatabase")]
    partial class UpdateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("module_20.DAL.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LecturerId = 1,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            LecturerId = 2,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 3,
                            LecturerId = 3,
                            Name = "Assembler x86"
                        },
                        new
                        {
                            Id = 4,
                            LecturerId = 4,
                            Name = "English Language"
                        });
                });

            modelBuilder.Entity("module_20.DAL.Entities.Homework", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LectureId")
                        .HasColumnType("int");

                    b.Property<int>("Mark")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LectureId");

                    b.HasIndex("StudentId");

                    b.ToTable("Homeworks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LectureId = 1,
                            Mark = 5,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            LectureId = 2,
                            Mark = 5,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            LectureId = 3,
                            Mark = 4,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 4,
                            LectureId = 4,
                            Mark = 4,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 5,
                            LectureId = 1,
                            Mark = 0,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 6,
                            LectureId = 2,
                            Mark = 0,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 7,
                            LectureId = 3,
                            Mark = 0,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 8,
                            LectureId = 4,
                            Mark = 0,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 9,
                            LectureId = 3,
                            Mark = 5,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 10,
                            LectureId = 4,
                            Mark = 5,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 11,
                            LectureId = 5,
                            Mark = 5,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 12,
                            LectureId = 6,
                            Mark = 5,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 13,
                            LectureId = 3,
                            Mark = 0,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 14,
                            LectureId = 4,
                            Mark = 0,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 15,
                            LectureId = 5,
                            Mark = 0,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 16,
                            LectureId = 6,
                            Mark = 0,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 17,
                            LectureId = 5,
                            Mark = 5,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 18,
                            LectureId = 6,
                            Mark = 5,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 19,
                            LectureId = 7,
                            Mark = 5,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 20,
                            LectureId = 5,
                            Mark = 5,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 21,
                            LectureId = 6,
                            Mark = 5,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 22,
                            LectureId = 7,
                            Mark = 5,
                            StudentId = 6
                        });
                });

            modelBuilder.Entity("module_20.DAL.Entities.Lecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lectures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Date = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "How to find a derivative?"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Date = new DateTime(2019, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Logarithmic Derivative"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 2,
                            Date = new DateTime(2019, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Introduction to the C# Language"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            Date = new DateTime(2019, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Creating types in C#"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 3,
                            Date = new DateTime(2019, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Introduction to the Assembler Language"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 3,
                            Date = new DateTime(2019, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "What is Register?"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 4,
                            Date = new DateTime(2019, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Present Simple"
                        });
                });

            modelBuilder.Entity("module_20.DAL.Entities.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lecturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ivanov@epam.com",
                            Mobile = "+7 (931) 945-23-45",
                            Name = "Ivanov Ivan Ivanovich"
                        },
                        new
                        {
                            Id = 2,
                            Email = "korobov@epam.com",
                            Mobile = "+7 (931) 955-23-45",
                            Name = "Korobov Andrew Ivanovich"
                        },
                        new
                        {
                            Id = 3,
                            Email = "burmistrov@epam.com",
                            Mobile = "+7 (931) 235-23-45",
                            Name = "Burmistrov Oleg Aleksandrovich"
                        },
                        new
                        {
                            Id = 4,
                            Email = "slavnov@epam.com",
                            Mobile = "+7 (931) 967-23-45",
                            Name = "Slavnov Nikita Alekseevich"
                        });
                });

            modelBuilder.Entity("module_20.DAL.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "kolen322@yandex.ru",
                            Mobile = "+7 (931) 945-23-45",
                            Name = "Vasyukhin Nikita"
                        },
                        new
                        {
                            Id = 2,
                            Email = "khebnev@mail.ru",
                            Mobile = "+7 (931) 965-23-45",
                            Name = "Khebnev Pavel"
                        },
                        new
                        {
                            Id = 3,
                            Email = "medvedevI@mail.ru",
                            Mobile = "+7 (931) 949-23-45",
                            Name = "Medvedev Ivan"
                        },
                        new
                        {
                            Id = 4,
                            Email = "ivanutinA@mail.ru",
                            Mobile = "+7 (931) 915-23-45",
                            Name = "Ivanutin Artem"
                        },
                        new
                        {
                            Id = 5,
                            Email = "malininV@mail.ru",
                            Mobile = "+7 (931) 945-63-45",
                            Name = "Malinin Vadim"
                        },
                        new
                        {
                            Id = 6,
                            Email = "suetovaE@mail.ru",
                            Mobile = "+7 (931) 948-23-45",
                            Name = "Suetova Elizavetha"
                        });
                });

            modelBuilder.Entity("module_20.DAL.Entities.StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourse");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 1,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 5,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 5,
                            CourseId = 4
                        },
                        new
                        {
                            StudentId = 6,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 6,
                            CourseId = 4
                        });
                });

            modelBuilder.Entity("module_20.DAL.Entities.StudentLecture", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("LectureId")
                        .HasColumnType("int");

                    b.Property<bool>("Attendance")
                        .HasColumnType("bit");

                    b.HasKey("StudentId", "LectureId");

                    b.HasIndex("LectureId");

                    b.ToTable("StudentLecture");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            LectureId = 1,
                            Attendance = true
                        },
                        new
                        {
                            StudentId = 1,
                            LectureId = 2,
                            Attendance = true
                        },
                        new
                        {
                            StudentId = 1,
                            LectureId = 3,
                            Attendance = true
                        },
                        new
                        {
                            StudentId = 1,
                            LectureId = 4,
                            Attendance = true
                        },
                        new
                        {
                            StudentId = 2,
                            LectureId = 1,
                            Attendance = false
                        },
                        new
                        {
                            StudentId = 2,
                            LectureId = 2,
                            Attendance = false
                        },
                        new
                        {
                            StudentId = 2,
                            LectureId = 3,
                            Attendance = false
                        },
                        new
                        {
                            StudentId = 2,
                            LectureId = 4,
                            Attendance = false
                        },
                        new
                        {
                            StudentId = 3,
                            LectureId = 3,
                            Attendance = true
                        },
                        new
                        {
                            StudentId = 3,
                            LectureId = 4,
                            Attendance = true
                        },
                        new
                        {
                            StudentId = 3,
                            LectureId = 5,
                            Attendance = true
                        },
                        new
                        {
                            StudentId = 3,
                            LectureId = 6,
                            Attendance = true
                        },
                        new
                        {
                            StudentId = 4,
                            LectureId = 3,
                            Attendance = true
                        },
                        new
                        {
                            StudentId = 4,
                            LectureId = 4,
                            Attendance = true
                        },
                        new
                        {
                            StudentId = 4,
                            LectureId = 5,
                            Attendance = true
                        },
                        new
                        {
                            StudentId = 4,
                            LectureId = 6,
                            Attendance = true
                        },
                        new
                        {
                            StudentId = 5,
                            LectureId = 5,
                            Attendance = true
                        },
                        new
                        {
                            StudentId = 5,
                            LectureId = 6,
                            Attendance = true
                        },
                        new
                        {
                            StudentId = 5,
                            LectureId = 7,
                            Attendance = true
                        },
                        new
                        {
                            StudentId = 6,
                            LectureId = 5,
                            Attendance = true
                        },
                        new
                        {
                            StudentId = 6,
                            LectureId = 6,
                            Attendance = true
                        },
                        new
                        {
                            StudentId = 6,
                            LectureId = 7,
                            Attendance = false
                        });
                });

            modelBuilder.Entity("module_20.DAL.Entities.Course", b =>
                {
                    b.HasOne("module_20.DAL.Entities.Lecturer", "Lecturer")
                        .WithMany("Courses")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("module_20.DAL.Entities.Homework", b =>
                {
                    b.HasOne("module_20.DAL.Entities.Lecture", "Lecture")
                        .WithMany("Homeworks")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("module_20.DAL.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("module_20.DAL.Entities.Lecture", b =>
                {
                    b.HasOne("module_20.DAL.Entities.Course", "Course")
                        .WithMany("Lectures")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("module_20.DAL.Entities.StudentCourse", b =>
                {
                    b.HasOne("module_20.DAL.Entities.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("module_20.DAL.Entities.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("module_20.DAL.Entities.StudentLecture", b =>
                {
                    b.HasOne("module_20.DAL.Entities.Lecture", "Lecture")
                        .WithMany("StudentLectures")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("module_20.DAL.Entities.Student", "Student")
                        .WithMany("StudentLectures")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
